name: build-linux
run-name: Building version v${{ inputs.version }} by @${{ github.actor }} for Linux
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v${{ inputs.version }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install  
      - name: Build app
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: |
            dist/exile-diary_${{ inputs.version }}_amd64.deb
            dist/latest-linux.yml